# Generated by Django 2.2.6 on 2019-11-12 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PBI',
            fields=[
                ('id', models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False)),
                ('story_pts', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=1)),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False)),
                ('total_story_points', models.IntegerField(default=0)),
                ('completed_story_points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=1)),
                ('priority', models.IntegerField(default=0)),
                ('pbi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.PBI')),
            ],
        ),
        migrations.CreateModel(
            name='TaskOwnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effort', models.IntegerField(default=0)),
                ('dev_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Developer')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=100)),
                ('manager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Manager')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Developer')),
            ],
        ),
        migrations.CreateModel(
            name='PBIsInSprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pbi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.PBI')),
                ('sprint_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='system.Sprint')),
            ],
        ),
        migrations.AddField(
            model_name='pbi',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Project'),
        ),
    ]
