# Generated by Django 2.2.6 on 2019-11-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='pbi_id',
            field=models.IntegerField(),
        ),
    ]
