# Generated by Django 2.2.6 on 2019-12-06 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_projectdevelopers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PBIsInSprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pbi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.PBI')),
                ('sprint_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='system.Sprint')),
            ],
        ),
    ]
