# Generated by Django 2.2.6 on 2019-11-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20191112_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
