# Generated by Django 2.2.6 on 2019-12-03 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0003_sprint_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskownership',
            name='dev_id',
        ),
        migrations.RemoveField(
            model_name='taskownership',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='name',
        ),
        migrations.AddField(
            model_name='developer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manager',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pbi',
            name='sprint_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.Sprint'),
        ),
        migrations.AddField(
            model_name='task',
            name='dev_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.Developer'),
        ),
        migrations.AddField(
            model_name='task',
            name='effort',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='PBIsInSprint',
        ),
        migrations.DeleteModel(
            name='TaskOwnership',
        ),
    ]
