# Generated by Django 2.2.6 on 2019-12-07 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_pbisinsprint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='dev_id',
            new_name='owner_id',
        ),
    ]
