# Generated by Django 2.2.6 on 2019-11-06 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20191103_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbi',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='manager_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Manager'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Developer'),
        ),
        migrations.AlterField(
            model_name='task',
            name='pbi_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.PBI'),
        ),
    ]
