# Generated by Django 2.2.6 on 2019-12-05 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0004_auto_20191204_0208'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=0, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='manager',
            name='user',
        ),
        migrations.AlterField(
            model_name='pbi',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pbis', to='system.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='manager_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.MultiUser'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='system.MultiUser'),
        ),
        migrations.AlterField(
            model_name='task',
            name='dev_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.MultiUser'),
        ),
        migrations.DeleteModel(
            name='Developer',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
