# Generated by Django 2.2.6 on 2019-12-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20191205_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiuser',
            name='user',
        ),
        migrations.AddField(
            model_name='multiuser',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='multiuser',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='multiuser',
            name='password',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='multiuser',
            name='username',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
