# Generated by Django 2.2.6 on 2019-12-05 04:28

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0006_auto_20191205_1224'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='multiuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='multiuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='multiuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='multiuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='multiuser',
            name='username',
        ),
        migrations.AddField(
            model_name='multiuser',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
