# Generated by Django 2.2.6 on 2019-11-06 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20191106_0505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Working',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Developer')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Task')),
            ],
        ),
    ]
